use std::{fmt::Debug, mem::transmute};

#[allow(dead_code)]
#[repr(u32)]
#[derive(Default, Copy, Clone)]
pub enum CardType {
    #[default]
    Peashooter = 0,
    Sunflower = 1,
    CherryBomb = 2,
    WallNut = 3,
    PotatoMine = 4,
    SnowPea = 5,
    Chomper = 6,
    Repeater = 7,
    PuffShroom = 8,
    SunShroom = 9,
    FumeShroom = 10,
    GraveBuster = 11,
    HypnoShroom = 12,
    ScaredyShroom = 13,
    IceShroom = 14,
    DoomShroom = 15,
    LilyPad = 16,
    Squash = 17,
    Threepeater = 18,
    TangleKelp = 19,
    Jalapeno = 20,
    Spikeweed = 21,
    Torchwood = 22,
    TallNut = 23,
    SeaShroom = 24,
    Plantern = 25,
    Cactus = 26,
    Blover = 27,
    SplitPea = 28,
    Starfruit = 29,
    Pumpkin = 30,
    MagnetShroom = 31,
    CabbagePult = 32,
    FlowerPot = 33,
    KernelPult = 34,
    CoffeeBean = 35,
    Garlic = 36,
    UmbrellaLeaf = 37,
    Marigold = 38,
    MelonPult = 39,
    GatlingPea = 40,
    TwinSunflower = 41,
    GloomShroom = 42,
    Cattail = 43,
    WinterMelon = 44,
    GoldMagnet = 45,
    Spikerock = 46,
    CobCannon = 47,
    ReverseRepeater = 52,

    ShufflePlants = 54,
    Crater = 55,
    Sun = 56,
    Diamond = 57,
    SnorkelZombie = 58,
    GoldTrophie = 59,
    Zombie = 60,
    ConeZombie = 61,
    PoleVaultingZombie = 62,
    BucketheadZombie = 63,
    LadderZombie = 64,
    DiggerZombie = 65,
    BungeeZombie = 66,
    FootballZombie = 67,
    BalloonZombie = 68,
    ScreenDoorZombie = 69,
    Zomboni = 70,
    PogoZombie = 71,
    DancingZombie = 72,
    GigaGargantuar = 73,
    Imp = 74,
}

impl Debug for CardType {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        let raw_value = unsafe { transmute::<&Self, &u32>(self) };
        if !matches!(raw_value, 0..=47 | 52 | 54..=74) {
            return write!(f, "{raw_value}");
        }

        match self {
            Self::Peashooter => write!(f, "Peashooter"),
            Self::Sunflower => write!(f, "Sunflower"),
            Self::CherryBomb => write!(f, "CherryBomb"),
            Self::WallNut => write!(f, "WallNut"),
            Self::PotatoMine => write!(f, "PotatoMine"),
            Self::SnowPea => write!(f, "SnowPea"),
            Self::Chomper => write!(f, "Chomper"),
            Self::Repeater => write!(f, "Repeater"),
            Self::PuffShroom => write!(f, "PuffShroom"),
            Self::SunShroom => write!(f, "SunShroom"),
            Self::FumeShroom => write!(f, "FumeShroom"),
            Self::GraveBuster => write!(f, "GraveBuster"),
            Self::HypnoShroom => write!(f, "HypnoShroom"),
            Self::ScaredyShroom => write!(f, "ScaredyShroom"),
            Self::IceShroom => write!(f, "IceShroom"),
            Self::DoomShroom => write!(f, "DoomShroom"),
            Self::LilyPad => write!(f, "LilyPad"),
            Self::Squash => write!(f, "Squash"),
            Self::Threepeater => write!(f, "Threepeater"),
            Self::TangleKelp => write!(f, "TangleKelp"),
            Self::Jalapeno => write!(f, "Jalapeno"),
            Self::Spikeweed => write!(f, "Spikeweed"),
            Self::Torchwood => write!(f, "Torchwood"),
            Self::TallNut => write!(f, "TallNut"),
            Self::SeaShroom => write!(f, "SeaShroom"),
            Self::Plantern => write!(f, "Plantern"),
            Self::Cactus => write!(f, "Cactus"),
            Self::Blover => write!(f, "Blover"),
            Self::SplitPea => write!(f, "SplitPea"),
            Self::Starfruit => write!(f, "Starfruit"),
            Self::Pumpkin => write!(f, "Pumpkin"),
            Self::MagnetShroom => write!(f, "MagnetShroom"),
            Self::CabbagePult => write!(f, "CabbagePult"),
            Self::FlowerPot => write!(f, "FlowerPot"),
            Self::KernelPult => write!(f, "KernelPult"),
            Self::CoffeeBean => write!(f, "CoffeeBean"),
            Self::Garlic => write!(f, "Garlic"),
            Self::UmbrellaLeaf => write!(f, "UmbrellaLeaf"),
            Self::Marigold => write!(f, "Marigold"),
            Self::MelonPult => write!(f, "MelonPult"),
            Self::GatlingPea => write!(f, "GatlingPea"),
            Self::TwinSunflower => write!(f, "TwinSunflower"),
            Self::GloomShroom => write!(f, "GloomShroom"),
            Self::Cattail => write!(f, "Cattail"),
            Self::WinterMelon => write!(f, "WinterMelon"),
            Self::GoldMagnet => write!(f, "GoldMagnet"),
            Self::Spikerock => write!(f, "Spikerock"),
            Self::CobCannon => write!(f, "CobCannon"),
            Self::ReverseRepeater => write!(f, "ReverseRepeater"),
            Self::ShufflePlants => write!(f, "ShufflePlants"),
            Self::Crater => write!(f, "Crater"),
            Self::Sun => write!(f, "Sun"),
            Self::Diamond => write!(f, "Diamond"),
            Self::SnorkelZombie => write!(f, "SnorkelZombie"),
            Self::GoldTrophie => write!(f, "GoldTrophie"),
            Self::Zombie => write!(f, "Zombie"),
            Self::ConeZombie => write!(f, "ConeZombie"),
            Self::PoleVaultingZombie => write!(f, "PoleVaultingZombie"),
            Self::BucketheadZombie => write!(f, "BucketheadZombie"),
            Self::LadderZombie => write!(f, "LadderZombie"),
            Self::DiggerZombie => write!(f, "DiggerZombie"),
            Self::BungeeZombie => write!(f, "BungeeZombie"),
            Self::FootballZombie => write!(f, "FootballZombie"),
            Self::BalloonZombie => write!(f, "BalloonZombie"),
            Self::ScreenDoorZombie => write!(f, "ScreenDoorZombie"),
            Self::Zomboni => write!(f, "Zomboni"),
            Self::PogoZombie => write!(f, "PogoZombie"),
            Self::DancingZombie => write!(f, "DancingZombie"),
            Self::GigaGargantuar => write!(f, "GigaGargantuar"),
            Self::Imp => write!(f, "Imp"),
        }
    }
}
