use std::fmt::Debug;

#[allow(dead_code)]
#[derive(Debug, Clone, Copy)]
pub enum PlantType {
    Peashooter,
    Sunflower,
    CherryBomb,
    WallNut,
    PotatoMine,
    SnowPea,
    Chomper,
    Repeater,
    PuffShroom,
    SunShroom,
    FumeShroom,
    GraveBuster,
    HypnoShroom,
    ScaredyShroom,
    IceShroom,
    DoomShroom,
    LilyPad,
    Squash,
    Threepeater,
    TangleKelp,
    Jalapeno,
    Spikeweed,
    Torchwood,
    TallNut,
    SeaShroom,
    Plantern,
    Cactus,
    Blover,
    SplitPea,
    Starfruit,
    Pumpkin,
    MagnetShroom,
    CabbagePult,
    FlowerPot,
    KernelPult,
    CoffeeBean,
    Garlic,
    UmbrellaLeaf,
    Marigold,
    MelonPult,
    GatlingPea,
    TwinSunflower,
    GloomShroom,
    Cattail,
    WinterMelon,
    GoldMagnet,
    Spikerock,
    CobCannon,
    ReverseRepeater,

    Unknown(u32),
}

impl Default for PlantType {
    fn default() -> Self {
        Self::Unknown(0)
    }
}

impl From<u32> for PlantType {
    fn from(value: u32) -> Self {
        match value {
            0 => Self::Peashooter,
            1 => Self::Sunflower,
            2 => Self::CherryBomb,
            3 => Self::WallNut,
            4 => Self::PotatoMine,
            5 => Self::SnowPea,
            6 => Self::Chomper,
            7 => Self::Repeater,
            8 => Self::PuffShroom,
            9 => Self::SunShroom,
            10 => Self::FumeShroom,
            11 => Self::GraveBuster,
            12 => Self::HypnoShroom,
            13 => Self::ScaredyShroom,
            14 => Self::IceShroom,
            15 => Self::DoomShroom,
            16 => Self::LilyPad,
            17 => Self::Squash,
            18 => Self::Threepeater,
            19 => Self::TangleKelp,
            20 => Self::Jalapeno,
            21 => Self::Spikeweed,
            22 => Self::Torchwood,
            23 => Self::TallNut,
            24 => Self::SeaShroom,
            25 => Self::Plantern,
            26 => Self::Cactus,
            27 => Self::Blover,
            28 => Self::SplitPea,
            29 => Self::Starfruit,
            30 => Self::Pumpkin,
            31 => Self::MagnetShroom,
            32 => Self::CabbagePult,
            33 => Self::FlowerPot,
            34 => Self::KernelPult,
            35 => Self::CoffeeBean,
            36 => Self::Garlic,
            37 => Self::UmbrellaLeaf,
            38 => Self::Marigold,
            39 => Self::MelonPult,
            40 => Self::GatlingPea,
            41 => Self::TwinSunflower,
            42 => Self::GloomShroom,
            43 => Self::Cattail,
            44 => Self::WinterMelon,
            45 => Self::GoldMagnet,
            46 => Self::Spikerock,
            47 => Self::CobCannon,
            52 => Self::ReverseRepeater,
            val => Self::Unknown(val),
        }
    }
}

impl From<PlantType> for u32 {
    fn from(value: PlantType) -> Self {
        match value {
            PlantType::Peashooter => 0,
            PlantType::Sunflower => 1,
            PlantType::CherryBomb => 2,
            PlantType::WallNut => 3,
            PlantType::PotatoMine => 4,
            PlantType::SnowPea => 5,
            PlantType::Chomper => 6,
            PlantType::Repeater => 7,
            PlantType::PuffShroom => 8,
            PlantType::SunShroom => 9,
            PlantType::FumeShroom => 10,
            PlantType::GraveBuster => 11,
            PlantType::HypnoShroom => 12,
            PlantType::ScaredyShroom => 13,
            PlantType::IceShroom => 14,
            PlantType::DoomShroom => 15,
            PlantType::LilyPad => 16,
            PlantType::Squash => 17,
            PlantType::Threepeater => 18,
            PlantType::TangleKelp => 19,
            PlantType::Jalapeno => 20,
            PlantType::Spikeweed => 21,
            PlantType::Torchwood => 22,
            PlantType::TallNut => 23,
            PlantType::SeaShroom => 24,
            PlantType::Plantern => 25,
            PlantType::Cactus => 26,
            PlantType::Blover => 27,
            PlantType::SplitPea => 28,
            PlantType::Starfruit => 29,
            PlantType::Pumpkin => 30,
            PlantType::MagnetShroom => 31,
            PlantType::CabbagePult => 32,
            PlantType::FlowerPot => 33,
            PlantType::KernelPult => 34,
            PlantType::CoffeeBean => 35,
            PlantType::Garlic => 36,
            PlantType::UmbrellaLeaf => 37,
            PlantType::Marigold => 38,
            PlantType::MelonPult => 39,
            PlantType::GatlingPea => 40,
            PlantType::TwinSunflower => 41,
            PlantType::GloomShroom => 42,
            PlantType::Cattail => 43,
            PlantType::WinterMelon => 44,
            PlantType::GoldMagnet => 45,
            PlantType::Spikerock => 46,
            PlantType::CobCannon => 47,
            PlantType::ReverseRepeater => 52,
            PlantType::Unknown(val) => val,
        }
    }
}
